// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-x-4K9bMTraX1BkFZfBI4BRYuHL3Rfbk',
    appId: '1:1068552120940:web:0df306517f229a7f740649',
    messagingSenderId: '1068552120940',
    projectId: 'kichikichi-3472d',
    authDomain: 'kichikichi-3472d.firebaseapp.com',
    storageBucket: 'kichikichi-3472d.firebasestorage.app',
    measurementId: 'G-JF4WFD82MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jbzHVdoB6OGh1bPO-ZIQ8iqbOApbyyM',
    appId: '1:1068552120940:android:65afdf167699db0f740649',
    messagingSenderId: '1068552120940',
    projectId: 'kichikichi-3472d',
    storageBucket: 'kichikichi-3472d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNKzKMKdmLJCvYeXDLcns2mbJ1px1F_rQ',
    appId: '1:1068552120940:ios:c07abaa2aa5eb329740649',
    messagingSenderId: '1068552120940',
    projectId: 'kichikichi-3472d',
    storageBucket: 'kichikichi-3472d.firebasestorage.app',
    iosBundleId: 'com.kichikichi.kichikichi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-x-4K9bMTraX1BkFZfBI4BRYuHL3Rfbk',
    appId: '1:1068552120940:web:0be1ce62a4aff4fe740649',
    messagingSenderId: '1068552120940',
    projectId: 'kichikichi-3472d',
    authDomain: 'kichikichi-3472d.firebaseapp.com',
    storageBucket: 'kichikichi-3472d.firebasestorage.app',
    measurementId: 'G-45LSS74K7C',
  );
}
