// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjP9DraHsQt9C2JfB8658f4A2wXQ1dCf0',
    appId: '1:606243318992:web:34c2ff77b3f2e6392602d5',
    messagingSenderId: '606243318992',
    projectId: 'pj1firebase',
    authDomain: 'pj1firebase.firebaseapp.com',
    storageBucket: 'pj1firebase.appspot.com',
    measurementId: 'G-XX2MW7SG4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoFOqNVIx8SvlpSi1ycgIXFH_XEdIombo',
    appId: '1:606243318992:android:75ecd6af12c32a1e2602d5',
    messagingSenderId: '606243318992',
    projectId: 'pj1firebase',
    storageBucket: 'pj1firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtCGGAGivFlVl8QLTaM6IbpORsGdCfeQ',
    appId: '1:606243318992:ios:4dbd53e6cabc4aa22602d5',
    messagingSenderId: '606243318992',
    projectId: 'pj1firebase',
    storageBucket: 'pj1firebase.appspot.com',
    iosBundleId: 'com.kichikichi.kichikichi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0TxIpMHE5tMlN8BgcBpV2yL52zaVfSF4',
    appId: '1:606243318992:web:9a6771b940336d4d2602d5',
    messagingSenderId: '606243318992',
    projectId: 'pj1firebase',
    authDomain: 'pj1firebase.firebaseapp.com',
    storageBucket: 'pj1firebase.appspot.com',
    measurementId: 'G-SW9YKSL0WY',
  );

}